version: '3'

services:
  logging-service-1:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 9000:8080
    environment:
      PAPERTRAIL_HOST: papertrailapp.com
      PAPERTRAIL_PORT: 1234
      PAPERTRAIL_APP: logging-service-1

  logging-service-2:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 9001:8080
    environment:
      PAPERTRAIL_HOST: papertrailapp.com
      PAPERTRAIL_PORT: 1234
      PAPERTRAIL_APP: logging-service-2

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
